apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - servicemonitor.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gitops-k8s-platform
images:
  - name: ghcr.io/davidmesamoyano/gitops-k8s-platform
    newTag: latest   # GitHub Actions cambia esta línea en cada push a main
